Minor fixes
Signed-off-by: Mingxiang Xue <mingxiangxue@gmail.com>

diff --git a/bin/ip b/bin/ip
--- a/bin/ip
+++ b/bin/ip
@@ -9,8 +9,9 @@ usage() {
 Wrapper for ip utility.
 
 Subcommands:
-  my - get the external IP of the current machine
-  geo - get the geo info of an IP
+  l, local - get the local IP of the current machine
+  my       - get the external IP of the current machine
+  geo      - get the geo info of an IP
 EOF
   exit 1
 }
@@ -21,6 +22,11 @@ PATH="$(new_path_exclude "$dotfiles_dir/bin")"
 usage_my() {
   cat <<-EOF
 Usage: ip my [--concise]
+
+**Updates**:
+
+The following methods seem not working anymore. Instead, we use 'httpbin.org'
+to find our public IP.
 
 Get the external IP of the current machine. We use below APIs to query:
 
@@ -52,29 +58,31 @@ cmd_my() {
       usage_my
   esac
 
-  # See https://www.ip138.com
-  local ip1=$(curl --silent 'https://202020.ip138.com/' \
-    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36' | \
-    xmllint --html --xpath "/html/head/title/text()" - 2>/dev/null | awk -F '：' '{print $2}')
+  # # See https://www.ip138.com
+  # local ip1=$(curl --silent 'https://202020.ip138.com/' \
+  #   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36' | \
+  #   xmllint --html --xpath "/html/head/title/text()" - 2>/dev/null | awk -F '：' '{print $2}')
+  #
+  # local ip2=$(curl --silent https://ipv4.icanhazip.com/)
+  #
+  # if [ -n "$ip1" -a -n "$ip2" -a ! "$ip1" = "$ip2" ]; then
+  #   if [ ! "$concise" = "1" ]; then
+  #     echo Got two different IP addresses:
+  #   fi
+  #   echo $ip1
+  #   echo $ip2
+  #   exit
+  # fi
+  #
+  # local ip
+  # if [ -n "$ip1" ]; then
+  #   ip="$ip1"
+  # fi
+  # if [ -n "$ip2" ]; then
+  #   ip="$ip2"
+  # fi
 
-  local ip2=$(curl --silent https://ipv4.icanhazip.com/)
-
-  if [ -n "$ip1" -a -n "$ip2" -a ! "$ip1" = "$ip2" ]; then
-    if [ ! "$concise" = "1" ]; then
-      echo Got two different IP addresses:
-    fi
-    echo $ip1
-    echo $ip2
-    exit
-  fi
-
-  local ip
-  if [ -n "$ip1" ]; then
-    ip="$ip1"
-  fi
-  if [ -n "$ip2" ]; then
-    ip="$ip2"
-  fi
+  ip="$(curl -s httpbin.org/get | jq -r '.origin')"
 
   echo "$ip" | tee >("$dotfiles_dir/bin/cb" >/dev/null)
   if [ ! "$concise" = "1" ]; then
@@ -113,6 +121,14 @@ cmd_geo() {
   fi
 }
 
+run_fallback() {
+  if ! type ip &>/dev/null; then
+    echo "Command ip not found."
+    exit 1
+  fi
+  ip "$@"
+}
+
 case "$1" in
   my | geo)
     cmd="$1"
@@ -130,9 +146,9 @@ case "$1" in
     ;;
   -)
     shift
-    ip "$@"
+    run_fallback "$@"
     ;;
   *)
-    ip "$@"
+    run_fallback "$@"
     ;;
 esac
