Check and install fzf

diff --git a/hooks/post-up b/hooks/post-up
--- a/hooks/post-up
+++ b/hooks/post-up
@@ -2,11 +2,23 @@
 #
 # This script will be evaluated after `rcup` finishes.
 
-echo 'Checking js-beautify for vim-autoformat json...'
-if type js-beautify >/dev/null; then
+echo -n 'Checking js-beautify for vim-autoformat json...'
+if type js-beautify &>/dev/null; then
   echo 'Found'
 else
   echo 'Not found, installing...'
   npm install -g js-beautify
   echo 'Done'
+fi
+
+echo -n 'Checking fzf...'
+if type fzf &>/dev/null; then
+  echo 'Found'
+else
+  echo 'Not found, installing...'
+  if `$(dirname $0)/../scripts/install_fzf.sh &>/dev/null`; then
+    echo 'Done'
+  else
+    exit 1
+  fi
 fi
