Refactor zshrc structure and add asdf
Signed-off-by: Mingxiang Xue <mingxiangxue@gmail.com>

diff --git a/hooks/post-up b/hooks/post-up
--- a/hooks/post-up
+++ b/hooks/post-up
@@ -14,6 +14,7 @@ abort() {
 case $OSTYPE in
   darwin*)
     platform=osx
+    [[ ! -e ~/.bin/vscode ]] && ln -s "/Applications/Visual Studio Code.app/Contents/MacOS/Electron" ~/.bin/vscode
     ;;
 esac
 
@@ -102,6 +103,18 @@ if type hstr &>/dev/null; then
 else
   echo 'Not found, installing...'
   if `$(dirname $0)/../scripts/install_hstr.sh >/dev/null`; then
+    echo 'Done'
+  else
+    exit 1
+  fi
+fi
+
+echo -n 'Checking rlwrap...'
+if type -p rlwrap &>/dev/null; then
+  echo 'Found'
+else
+  echo 'Not found, installing...'
+  if `$(dirname $0)/../scripts/install_rlwrap.sh >/dev/null`; then
     echo 'Done'
   else
     exit 1
