Add hook to install netcat and socat

diff --git a/hooks/post-up b/hooks/post-up
--- a/hooks/post-up
+++ b/hooks/post-up
@@ -33,6 +33,27 @@ fi
 erb -T - $(dirname $0)/../vim/vimrc.generated.erb >~/.vim/vimrc.generated
 erb -T - $(dirname $0)/../config/nvim/coc-settings.json.erb >~/.config/nvim/coc-settings.json
 
+echo -n 'Checking netcat...'
+if type -p nc &>/dev/null; then
+  echo 'Found'
+elif type -p netcat &>/dev/null; then
+  echo 'Found'
+else
+  abort 'Please ensure netcat installed'
+fi
+
+echo -n 'Checking socat...'
+if type -p socat &>/dev/null; then
+  echo 'Found'
+else
+  echo 'Not found, installing...'
+  if `$(dirname $0)/../scripts/install_socat.sh >/dev/null`; then
+    echo 'Done'
+  else
+    exit 1
+  fi
+fi
+
 echo -n 'Checking antibody...'
 if type antibody &>/dev/null; then
   echo 'Found'
